CREATE TABLE IF NOT EXISTS `marketing_email_batch` (
    `id` BIGINT NOT NULL COMMENT '编号',
    `tenant_id` BIGINT DEFAULT NULL COMMENT '租户ID',
    `campaign_id` BIGINT DEFAULT NULL COMMENT '活动ID',
    `campaign_name` VARCHAR(255) DEFAULT NULL COMMENT '活动名称',
    `template_id` BIGINT NOT NULL COMMENT '模板ID',
    `template_name` VARCHAR(255) DEFAULT NULL COMMENT '模板名称',
    `subject` VARCHAR(500) NOT NULL COMMENT '邮件主题',
    `content` LONGTEXT NOT NULL COMMENT '邮件内容',
    `status` TINYINT DEFAULT 0 COMMENT '状态（0-待发送 1-发送中 2-已完成 3-发送失败）',
    `total_count` INT DEFAULT 0 COMMENT '目标总数',
    `send_count` INT DEFAULT 0 COMMENT '已发送数',
    `success_count` INT DEFAULT 0 COMMENT '成功数',
    `fail_count` INT DEFAULT 0 COMMENT '失败数',
    `send_time` VARCHAR(50) DEFAULT NULL COMMENT '发送时间',
    `error_message` VARCHAR(1000) DEFAULT NULL COMMENT '错误信息',
    `creator` VARCHAR(64) DEFAULT NULL COMMENT '创建者',
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updater` VARCHAR(64) DEFAULT NULL COMMENT '更新者',
    `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` TINYINT DEFAULT 0 COMMENT '是否删除',
    PRIMARY KEY (`id`),
    INDEX `idx_campaign_id` (`campaign_id`),
    INDEX `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='营销邮件批次表';