-- 修复财务域菜单中文显示乱码。导入前请确认客户端使用 UTF-8。
SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;

UPDATE `system_menu` SET `name` = '发票管理' WHERE `id` = 5100;
UPDATE `system_menu` SET `name` = '发票查询' WHERE `id` = 5101;
UPDATE `system_menu` SET `name` = '发票创建' WHERE `id` = 5102;
UPDATE `system_menu` SET `name` = '发票更新' WHERE `id` = 5103;
UPDATE `system_menu` SET `name` = '发票删除' WHERE `id` = 5104;
UPDATE `system_menu` SET `name` = '发票导出' WHERE `id` = 5105;
UPDATE `system_menu` SET `name` = '发票审核' WHERE `id` = 5106;
UPDATE `system_menu` SET `name` = '报销管理' WHERE `id` = 5110;
UPDATE `system_menu` SET `name` = '报销查询' WHERE `id` = 5111;
UPDATE `system_menu` SET `name` = '报销创建' WHERE `id` = 5112;
UPDATE `system_menu` SET `name` = '报销更新' WHERE `id` = 5113;
UPDATE `system_menu` SET `name` = '报销删除' WHERE `id` = 5114;
UPDATE `system_menu` SET `name` = '报销导出' WHERE `id` = 5115;
UPDATE `system_menu` SET `name` = '报销审批' WHERE `id` = 5116;
UPDATE `system_menu` SET `name` = '退款管理' WHERE `id` = 5120;
UPDATE `system_menu` SET `name` = '退款查询' WHERE `id` = 5121;
UPDATE `system_menu` SET `name` = '退款创建' WHERE `id` = 5122;
UPDATE `system_menu` SET `name` = '退款更新' WHERE `id` = 5123;
UPDATE `system_menu` SET `name` = '退款删除' WHERE `id` = 5124;
UPDATE `system_menu` SET `name` = '退款导出' WHERE `id` = 5125;
UPDATE `system_menu` SET `name` = '退款审批' WHERE `id` = 5126;
UPDATE `system_menu` SET `name` = '费用管理' WHERE `id` = 5130;
UPDATE `system_menu` SET `name` = '费用查询' WHERE `id` = 5131;
UPDATE `system_menu` SET `name` = '费用创建' WHERE `id` = 5132;
UPDATE `system_menu` SET `name` = '费用更新' WHERE `id` = 5133;
UPDATE `system_menu` SET `name` = '费用删除' WHERE `id` = 5134;
UPDATE `system_menu` SET `name` = '费用导出' WHERE `id` = 5135;
UPDATE `system_menu` SET `name` = '费用审核' WHERE `id` = 5136;
UPDATE `system_menu` SET `name` = '财务分析' WHERE `id` = 5140;

UPDATE `system_menu_i18n` SET `name` = '发票管理' WHERE `menu_id` = 5100 AND `language` = 'zh-CN';
UPDATE `system_menu_i18n` SET `name` = '发票查询' WHERE `menu_id` = 5101 AND `language` = 'zh-CN';
UPDATE `system_menu_i18n` SET `name` = '发票创建' WHERE `menu_id` = 5102 AND `language` = 'zh-CN';
UPDATE `system_menu_i18n` SET `name` = '发票更新' WHERE `menu_id` = 5103 AND `language` = 'zh-CN';
UPDATE `system_menu_i18n` SET `name` = '发票删除' WHERE `menu_id` = 5104 AND `language` = 'zh-CN';
UPDATE `system_menu_i18n` SET `name` = '发票导出' WHERE `menu_id` = 5105 AND `language` = 'zh-CN';
UPDATE `system_menu_i18n` SET `name` = '发票审核' WHERE `menu_id` = 5106 AND `language` = 'zh-CN';
UPDATE `system_menu_i18n` SET `name` = '报销管理' WHERE `menu_id` = 5110 AND `language` = 'zh-CN';
UPDATE `system_menu_i18n` SET `name` = '报销查询' WHERE `menu_id` = 5111 AND `language` = 'zh-CN';
UPDATE `system_menu_i18n` SET `name` = '报销创建' WHERE `menu_id` = 5112 AND `language` = 'zh-CN';
UPDATE `system_menu_i18n` SET `name` = '报销更新' WHERE `menu_id` = 5113 AND `language` = 'zh-CN';
UPDATE `system_menu_i18n` SET `name` = '报销删除' WHERE `menu_id` = 5114 AND `language` = 'zh-CN';
UPDATE `system_menu_i18n` SET `name` = '报销导出' WHERE `menu_id` = 5115 AND `language` = 'zh-CN';
UPDATE `system_menu_i18n` SET `name` = '报销审批' WHERE `menu_id` = 5116 AND `language` = 'zh-CN';
UPDATE `system_menu_i18n` SET `name` = '退款管理' WHERE `menu_id` = 5120 AND `language` = 'zh-CN';
UPDATE `system_menu_i18n` SET `name` = '退款查询' WHERE `menu_id` = 5121 AND `language` = 'zh-CN';
UPDATE `system_menu_i18n` SET `name` = '退款创建' WHERE `menu_id` = 5122 AND `language` = 'zh-CN';
UPDATE `system_menu_i18n` SET `name` = '退款更新' WHERE `menu_id` = 5123 AND `language` = 'zh-CN';
UPDATE `system_menu_i18n` SET `name` = '退款删除' WHERE `menu_id` = 5124 AND `language` = 'zh-CN';
UPDATE `system_menu_i18n` SET `name` = '退款导出' WHERE `menu_id` = 5125 AND `language` = 'zh-CN';
UPDATE `system_menu_i18n` SET `name` = '退款审批' WHERE `menu_id` = 5126 AND `language` = 'zh-CN';
UPDATE `system_menu_i18n` SET `name` = '费用管理' WHERE `menu_id` = 5130 AND `language` = 'zh-CN';
UPDATE `system_menu_i18n` SET `name` = '费用查询' WHERE `menu_id` = 5131 AND `language` = 'zh-CN';
UPDATE `system_menu_i18n` SET `name` = '费用创建' WHERE `menu_id` = 5132 AND `language` = 'zh-CN';
UPDATE `system_menu_i18n` SET `name` = '费用更新' WHERE `menu_id` = 5133 AND `language` = 'zh-CN';
UPDATE `system_menu_i18n` SET `name` = '费用删除' WHERE `menu_id` = 5134 AND `language` = 'zh-CN';
UPDATE `system_menu_i18n` SET `name` = '费用导出' WHERE `menu_id` = 5135 AND `language` = 'zh-CN';
UPDATE `system_menu_i18n` SET `name` = '费用审核' WHERE `menu_id` = 5136 AND `language` = 'zh-CN';
UPDATE `system_menu_i18n` SET `name` = '财务分析' WHERE `menu_id` = 5140 AND `language` = 'zh-CN';
