UPDATE ACT_HI_VARINST 
SET LONG_ = 3, TEXT_ = '3'
WHERE PROC_INST_ID_ IN (
    SELECT PROC_INST_ID_ FROM ACT_HI_PROCINST 
    WHERE END_TIME_ IS NOT NULL 
      AND PROC_DEF_ID_ LIKE 'oa_%'
) AND NAME_ = 'PROCESS_STATUS' AND LONG_ = 1;
