UPDATE ACT_HI_PROCINST 
SET END_TIME_ = NOW(), DELETE_REASON_ = 'FORCE_CLOSE'
WHERE END_TIME_ IS NULL 
  AND PROC_DEF_ID_ LIKE 'oa_%'
  AND PROC_INST_ID_ NOT IN (SELECT PROC_INST_ID_ FROM ACT_RU_EXECUTION WHERE PROC_DEF_ID_ LIKE 'oa_%');
