server:
  port: 8080

spring:
  autoconfigure:
    exclude:
      - org.springframework.ai.vectorstore.qdrant.autoconfigure.QdrantVectorStoreAutoConfiguration
      - org.springframework.ai.vectorstore.milvus.autoconfigure.MilvusVectorStoreAutoConfiguration
  datasource:
    druid:
      web-stat-filter:
        enabled: true
      stat-view-servlet:
        enabled: true
        allow:
        url-pattern: /druid/*
        login-username:
        login-password:
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 100
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
    dynamic:
      druid:
        initial-size: 5
        min-idle: 10
        max-active: 20
        max-wait: 60000
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 600000
        max-evictable-idle-time-millis: 1800000
        validation-query: SELECT 1 FROM DUAL
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
      primary: master
      datasource:
        master:
          url: jdbc:mysql://127.0.0.1:3306/mitedtsm_database?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true&rewriteBatchedStatements=true
          username: root
          password: 1234
        slave:
          lazy: true
          url: jdbc:mysql://127.0.0.1:3306/mitedtsm_database?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true&rewriteBatchedStatements=true
          username: root
          password: 1234
        tdengine:
          lazy: true
          url: jdbc:TAOS-WS://127.0.0.1:6041/mitedtsm_database?varcharAsString=true
          driver-class-name: com.taosdata.jdbc.ws.WebSocketDriver
          username: root
          password: taosdata
          druid:
            validation-query: SELECT SERVER_STATUS()
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 1
  quartz:
    auto-startup: true
    scheduler-name: schedulerName
    job-store-type: jdbc
    wait-for-jobs-to-complete-on-shutdown: true
    properties:
      org:
        quartz:
          scheduler:
            instanceName: schedulerName
            instanceId: AUTO
          jobStore:
            class: org.springframework.scheduling.quartz.LocalDataSourceJobStore
            isClustered: true
            clusterCheckinInterval: 15000
            misfireThreshold: 60000
          threadPool:
            threadCount: 25
            threadPriority: 5
            class: org.quartz.simpl.SimpleThreadPool
    jdbc:
      initialize-schema: NEVER
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  kafka:
    bootstrap-servers: 127.0.0.1:9092
  boot:
    admin:
      client:
        url: http://127.0.0.1:${server.port}/${spring.boot.admin.context-path}
        instance:
          service-host-type: IP
        username: admin
        password: admin
      context-path: /admin

rocketmq:
  name-server: 127.0.0.1:9876

lock4j:
  acquire-timeout: 3000
  expire: 30000

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'

logging:
  file:
    name: ./logs/${spring.application.name}.log

wx:
  mp:
    app-id: wx041349c6f39b268b
    secret: 5abee519483bc9f8cb37ce280e814bd0
    config-storage:
      type: RedisTemplate
      key-prefix: wx
      http-client-type: HttpClient
  miniapp:
    appid: wx63c280fe3248a3e7
    secret: 6f270509224a7ae1296bbf1c8cb97aed
    config-storage:
      type: RedisTemplate
      key-prefix: wa
      http-client-type: HttpClient

mitedtsm:
  pay:
    order-notify-url: http://yunai.natapp1.cc/admin-api/pay/notify/order
    refund-notify-url: http://yunai.natapp1.cc/admin-api/pay/notify/refund
    transfer-notify-url: https://yunai.natapp1.cc/admin-api/pay/notify/transfer
  demo: false
  tencent-lbs-key: TVDBZ-TDILD-4ON4B-PFDZA-RNLKH-VVF6E

justauth:
  enabled: true
  type:
    DINGTALK:
      client-id: dingvrnreaje3yqvzhxg
      client-secret: i8E6iZyDvZj51JIb0tYsYfVQYOks9Cq1lgryEjFRqC79P3iJcrxEwT6Qk2QvLrLI
      ignore-check-redirect-uri: true
    WECHAT_ENTERPRISE:
      client-id: wwd411c69a39ad2e54
      client-secret: 1wTb7hYxnpT2TUbIeHGXGo7T0odav1ic10mLdyyATOw
      agent-id: 1000004
      ignore-check-redirect-uri: true
    WECHAT_MINI_PROGRAM:
      client-id: ${wx.miniapp.appid}
      client-secret: ${wx.miniapp.secret}
      ignore-check-redirect-uri: true
      ignore-check-state: true
    WECHAT_MP:
      client-id: ${wx.mp.app-id}
      client-secret: ${wx.mp.secret}
      ignore-check-redirect-uri: true
    ALIPAY:
      client-id: xx
      client-secret: xx
      alipay-public-key: xx
      ignore-check-redirect-uri: true
      ignore-check-state: true
  cache:
    type: REDIS
    prefix: 'social_auth_state:'
    timeout: 24h